# 輸入，路徑下的 .log 都輸入給 logstah
# filebeat 下載地址
# https://www.elastic.co/cn/downloads/past-releases/filebeat-7-17-7/
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - ./*.log
# 輸出給logstash
output.logstash:
  hosts: ["localhost:5044"]