# 輸入
# filebeat 下載地址
# https://www.elastic.co/cn/downloads/past-releases/filebeat-7-9-3/
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - ./*.log
# 輸出
output.logstash:
  hosts: ["localhost:5044"]